# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import py_rpc_pb2 as py__rpc__pb2


class PyRPCServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextToSpeech = channel.unary_unary(
                '/PyRPC.PyRPCService/TextToSpeech',
                request_serializer=py__rpc__pb2.TTSInput.SerializeToString,
                response_deserializer=py__rpc__pb2.TTSOutput.FromString,
                )
        self.SpeechToText = channel.unary_unary(
                '/PyRPC.PyRPCService/SpeechToText',
                request_serializer=py__rpc__pb2.STTInput.SerializeToString,
                response_deserializer=py__rpc__pb2.STTOutput.FromString,
                )
        self.RespondToText = channel.unary_unary(
                '/PyRPC.PyRPCService/RespondToText',
                request_serializer=py__rpc__pb2.ConversationInput.SerializeToString,
                response_deserializer=py__rpc__pb2.ConversationResponse.FromString,
                )


class PyRPCServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def TextToSpeech(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeechToText(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondToText(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PyRPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TextToSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.TextToSpeech,
                    request_deserializer=py__rpc__pb2.TTSInput.FromString,
                    response_serializer=py__rpc__pb2.TTSOutput.SerializeToString,
            ),
            'SpeechToText': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechToText,
                    request_deserializer=py__rpc__pb2.STTInput.FromString,
                    response_serializer=py__rpc__pb2.STTOutput.SerializeToString,
            ),
            'RespondToText': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondToText,
                    request_deserializer=py__rpc__pb2.ConversationInput.FromString,
                    response_serializer=py__rpc__pb2.ConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PyRPC.PyRPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PyRPCService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def TextToSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyRPC.PyRPCService/TextToSpeech',
            py__rpc__pb2.TTSInput.SerializeToString,
            py__rpc__pb2.TTSOutput.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SpeechToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyRPC.PyRPCService/SpeechToText',
            py__rpc__pb2.STTInput.SerializeToString,
            py__rpc__pb2.STTOutput.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RespondToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyRPC.PyRPCService/RespondToText',
            py__rpc__pb2.ConversationInput.SerializeToString,
            py__rpc__pb2.ConversationResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
