# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seq2seq_service.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='seq2seq_service.proto',
    package='Seq2SeqGRPC',
    syntax='proto3',
    serialized_options=_b('\242\002\003RTG'),
    serialized_pb=_b(
        '\n\x15seq2seq_service.proto\x12\x0bSeq2SeqGRPC\"3\n\x11\x43onversationInput\x12\x10\n\x08trans_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\xa0\x01\n\x14\x43onversationResponse\x12\x10\n\x08trans_id\x18\x01 \x01(\t\x12\x36\n\x05state\x18\x02 \x01(\x0e\x32\'.Seq2SeqGRPC.ConversationResponse.State\x12\x0c\n\x04text\x18\x03 \x01(\t\"0\n\x05State\x12\x0b\n\x07SUCCESS\x10\x00\x12\r\n\tMODEL_ERR\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x32\x64\n\x0eSeq2SeqService\x12R\n\rRespondToText\x12\x1e.Seq2SeqGRPC.ConversationInput\x1a!.Seq2SeqGRPC.ConversationResponseB\x06\xa2\x02\x03RTGb\x06proto3'
    )
)

_CONVERSATIONRESPONSE_STATE = _descriptor.EnumDescriptor(
    name='State',
    full_name='Seq2SeqGRPC.ConversationResponse.State',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='SUCCESS',
            index=0,
            number=0,
            serialized_options=None,
            type=None
        ),
        _descriptor.EnumValueDescriptor(
            name='MODEL_ERR',
            index=1,
            number=1,
            serialized_options=None,
            type=None
        ),
        _descriptor.EnumValueDescriptor(
            name='UNKNOWN',
            index=2,
            number=2,
            serialized_options=None,
            type=None
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=204,
    serialized_end=252,
)
_sym_db.RegisterEnumDescriptor(_CONVERSATIONRESPONSE_STATE)

_CONVERSATIONINPUT = _descriptor.Descriptor(
    name='ConversationInput',
    full_name='Seq2SeqGRPC.ConversationInput',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='trans_id',
            full_name='Seq2SeqGRPC.ConversationInput.trans_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR
        ),
        _descriptor.FieldDescriptor(
            name='text',
            full_name='Seq2SeqGRPC.ConversationInput.text',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=38,
    serialized_end=89,
)

_CONVERSATIONRESPONSE = _descriptor.Descriptor(
    name='ConversationResponse',
    full_name='Seq2SeqGRPC.ConversationResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='trans_id',
            full_name='Seq2SeqGRPC.ConversationResponse.trans_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR
        ),
        _descriptor.FieldDescriptor(
            name='state',
            full_name='Seq2SeqGRPC.ConversationResponse.state',
            index=1,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR
        ),
        _descriptor.FieldDescriptor(
            name='text',
            full_name='Seq2SeqGRPC.ConversationResponse.text',
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _CONVERSATIONRESPONSE_STATE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=92,
    serialized_end=252,
)

_CONVERSATIONRESPONSE.fields_by_name['state'
                                    ].enum_type = _CONVERSATIONRESPONSE_STATE
_CONVERSATIONRESPONSE_STATE.containing_type = _CONVERSATIONRESPONSE
DESCRIPTOR.message_types_by_name['ConversationInput'] = _CONVERSATIONINPUT
DESCRIPTOR.message_types_by_name['ConversationResponse'] = _CONVERSATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConversationInput = _reflection.GeneratedProtocolMessageType(
    'ConversationInput',
    (_message.Message, ),
    {
        'DESCRIPTOR': _CONVERSATIONINPUT,
        '__module__': 'seq2seq_service_pb2'
        # @@protoc_insertion_point(class_scope:Seq2SeqGRPC.ConversationInput)
    }
)
_sym_db.RegisterMessage(ConversationInput)

ConversationResponse = _reflection.GeneratedProtocolMessageType(
    'ConversationResponse',
    (_message.Message, ),
    {
        'DESCRIPTOR': _CONVERSATIONRESPONSE,
        '__module__': 'seq2seq_service_pb2'
        # @@protoc_insertion_point(class_scope:Seq2SeqGRPC.ConversationResponse)
    }
)
_sym_db.RegisterMessage(ConversationResponse)

DESCRIPTOR._options = None

_SEQ2SEQSERVICE = _descriptor.ServiceDescriptor(
    name='Seq2SeqService',
    full_name='Seq2SeqGRPC.Seq2SeqService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=254,
    serialized_end=354,
    methods=[
        _descriptor.MethodDescriptor(
            name='RespondToText',
            full_name='Seq2SeqGRPC.Seq2SeqService.RespondToText',
            index=0,
            containing_service=None,
            input_type=_CONVERSATIONINPUT,
            output_type=_CONVERSATIONRESPONSE,
            serialized_options=None,
        ),
    ]
)
_sym_db.RegisterServiceDescriptor(_SEQ2SEQSERVICE)

DESCRIPTOR.services_by_name['Seq2SeqService'] = _SEQ2SEQSERVICE

# @@protoc_insertion_point(module_scope)
