# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import text2speech_service_pb2 as text2speech__service__pb2


class Text2SpeechServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextToSpeech = channel.unary_unary(
                '/Text2SpeechRPC.Text2SpeechService/TextToSpeech',
                request_serializer=text2speech__service__pb2.TTSInput.SerializeToString,
                response_deserializer=text2speech__service__pb2.TTSOutput.FromString,
                )


class Text2SpeechServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def TextToSpeech(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Text2SpeechServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TextToSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.TextToSpeech,
                    request_deserializer=text2speech__service__pb2.TTSInput.FromString,
                    response_serializer=text2speech__service__pb2.TTSOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Text2SpeechRPC.Text2SpeechService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Text2SpeechService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def TextToSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Text2SpeechRPC.Text2SpeechService/TextToSpeech',
            text2speech__service__pb2.TTSInput.SerializeToString,
            text2speech__service__pb2.TTSOutput.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
